### PR TITLE
Don't process dpkg files in the /etc/clearwater/features.d directory

### PR DESCRIPTION
**Pull request by dtheobald**
During system test we have a tendency to install a load on a pre-configured system (i.e. edited /etc/clearwater/features.d files, etc.) which causes dpkg to deposit files like - \*.dpkg-dist, etc - in that directory which are (were) read by the features.d logic in the init.d scripts. This causes undesired configuration when the \*.dpkg-\* files contain different setting than those pre-configured, so I modified all init.d scripts to ignore \*.dpkg-\* files when processing the featured.d directory.

### CODE REVIEW

**Comment by AlexHockey** [comment]
I think you're saying that in testing you manually modify the features files, and when you upgrade dpkg saves off a version in the features.d directory, which causes incorrect configuration. So my question is - why are you modifying the features files? They are baked into the CC packages and not meant to be changed, right?

**Comment by dtheobald** [comment]
I was making this change in crest just to be consistent with the other scripts that process the features.d. directory.

**Comment by AlexHockey** [comment]
Of all the PRs that related to the features.d directory this was the only one that had an explanation of why the change was required. That's why I asked my questions here. I think the questions are valid nevertheless.

**Comment by AlexHockey** [comment]
Doug, I'm assigning this back to you to answer my question about how you ended up with rogue files in the first place.

**Comment by AlexHockey** [comment]
Ping @dtheobald

**Pull request closed without merging**
